<a href="https://colab.research.google.com/github/AyushKatochh/Python-Programs/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install pycaret &> /dev/null

In [3]:
from pycaret.datasets import get_data
dataSets = get_data("index")

                             Dataset    Data Types  ... # Attributes Missing Values
0                            anomaly  Multivariate  ...           10              N
1                             france  Multivariate  ...            8              N
2                            germany  Multivariate  ...            8              N
3                               bank  Multivariate  ...           17              N
4                              blood  Multivariate  ...            5              N
5                             cancer  Multivariate  ...           10              N
6                             credit  Multivariate  ...           24              N
7                           diabetes  Multivariate  ...            9              N
8                    electrical_grid  Multivariate  ...           14              N
9                           employee  Multivariate  ...           10              N
10                             heart  Multivariate  ...           16              N
11                     heart_disease  Multivariate  ...           14              N
12                         hepatitis  Multivariate  ...           32              Y
13                            income  Multivariate  ...           14              Y
14                             juice  Multivariate  ...           15              N
15                               nba  Multivariate  ...           21              N
16                              wine  Multivariate  ...           13              N
17                         telescope  Multivariate  ...           11              N
18                           titanic  Multivariate  ...           11              Y
19  us_presidential_election_results  Multivariate  ...            7              N
20                             glass  Multivariate  ...           10              N
21                              iris  Multivariate  ...            5              N
22                             poker  Multivariate  ...           11              N
23                         questions  Multivariate  ...            4              N
24                         satellite  Multivariate  ...           37              N
25                               CTG  Multivariate  ...           40              Y
26                          asia_gdp  Multivariate  ...           11              N
27                         elections  Multivariate  ...           54              Y
28                          facebook  Multivariate  ...           12              N
29                               ipl  Multivariate  ...           25              N
30                         jewellery  Multivariate  ...            4              N
31                              mice  Multivariate  ...           82              Y
32                         migration  Multivariate  ...           12              N
33                           perfume  Multivariate  ...           29              N
34                           pokemon  Multivariate  ...           13              Y
35                        population  Multivariate  ...           56              Y
36                     public_health  Multivariate  ...           21              N
37                             seeds  Multivariate  ...            7              N
38                         wholesale  Multivariate  ...            8              N
39                            tweets          Text  ...            2              N
40                            amazon          Text  ...            2              N
41                              kiva          Text  ...            7              N
42                               spx          Text  ...            4              N
43                         wikipedia          Text  ...            3              N
44                        automobile  Multivariate  ...           26              Y
45                              bike  Multivariate  ...           15              N
46                            boston  Multivariate  ...           14              N
47                          concrete  Multivariate  ...            9              N
48                           diamond  Multivariate  ...            8              N
49                            energy  Multivariate  ...           10              N
50                            forest  Multivariate  ...           13              N
51                              gold  Multivariate  ...          121              N
52                             house  Multivariate  ...           81              Y
53                         insurance  Multivariate  ...            7              N
54                        parkinsons  Multivariate  ...           22              N
55                           traffic  Multivariate  ...            8              N

[56 rows x 8 columns]

In [4]:
iris_1 = get_data("iris")

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
# Initialize Setup
from pycaret.classification import *

#Perimeter setting for all classification models
s_model = setup(data = iris_1, target="species", silent=True)

                               Description                                              Value
0                               session_id                                               7473
1                                   Target                                            species
2                              Target Type                                         Multiclass
3                            Label Encoded  Iris-setosa: 0, Iris-versicolor: 1, Iris-virgi...
4                            Original Data                                           (150, 5)
5                           Missing Values                                              False
6                         Numeric Features                                                  4
7                     Categorical Features                                                  0
8                         Ordinal Features                                              False
9                High Cardinality Features                                              False
10                 High Cardinality Method                                               None
11                   Transformed Train Set                                           (104, 4)
12                    Transformed Test Set                                            (46, 4)
13                      Shuffle Train-Test                                               True
14                     Stratify Train-Test                                              False
15                          Fold Generator                                    StratifiedKFold
16                             Fold Number                                                 10
17                                CPU Jobs                                                 -1
18                                 Use GPU                                              False
19                          Log Experiment                                              False
20                         Experiment Name                                   clf-default-name
21                                     USI                                               c52e
22                         Imputation Type                                             simple
23          Iterative Imputation Iteration                                               None
24                         Numeric Imputer                                               mean
25      Iterative Imputation Numeric Model                                               None
26                     Categorical Imputer                                           constant
27  Iterative Imputation Categorical Model                                               None
28           Unknown Categoricals Handling                                     least_frequent
29                               Normalize                                              False
30                        Normalize Method                                               None
31                          Transformation                                              False
32                   Transformation Method                                               None
33                                     PCA                                              False
34                              PCA Method                                               None
35                          PCA Components                                               None
36                     Ignore Low Variance                                              False
37                     Combine Rare Levels                                              False
38                    Rare Level Threshold                                               None
39                         Numeric Binning                                              False
40                         Remove Outliers                                              False
41                      Outliers Threshold                                               None
42                Remove Multicollinearity                                              False
43             Multicollinearity Threshold                                               None
44             Remove Perfect Collinearity                                               True
45                              Clustering                                              False
46                    Clustering Iteration                                               None
47                     Polynomial Features                                              False
48                       Polynomial Degree                                               None
49                    Trignometry Features                                              False
50                    Polynomial Threshold                                               None
51                          Group Features                                              False
52                       Feature Selection                                              False
53                Feature Selection Method                                            classic
54            Features Selection Threshold                                               None
55                     Feature Interaction                                              False
56                           Feature Ratio                                              False
57                   Interaction Threshold                                               None
58                           Fix Imbalance                                              False
59                    Fix Imbalance Method                                              SMOTE